In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix, accuracy_score, precision_score, recall_score

In [2]:
df = pd.read_csv("C:\DSBDA\Practicals\Pandas\Social_Media_Advertising (1).csv")

In [3]:
df

,Campaign_ID,Gender,Age Group,Campaign_Goal,Duration,Channel_Used,Conversion_Rate,Acquisition_Cost,ROI,Location,Language,Clicks,Impressions,Engagement_Score,Customer_Segment,Date,Company,CTR,Performance Tier
0,529013,Men,35-44,Product Launch,15 Days,Instagram,0.15,500,5.790000,Las Vegas,Spanish,500,3000,7,Health,25/02/2022,Aura Align,0.166667,High
1,275352,Women,45-60,Market Expansion,15 Days,Facebook,0.01,500,7.210000,Los Angeles,French,500,3000,5,Home,12/05/2022,Hearth Harmony,0.166667,High
2,692322,Men,45-60,Product Launch,15 Days,Instagram,0.08,500,0.430000,Austin,Spanish,500,3000,9,Technology,19/06/2022,Cyber Circuit,0.166667,Low
3,675757,Men,25-34,Increase Sales,15 Days,Pinterest,0.03,500,0.909824,Miami,Spanish,293,1937,1,Health,08/09/2022,Well Wish,0.151265,Low
4,535900,Men,45-60,Market Expansion,15 Days,Pinterest,0.13,500,1.422828,Austin,French,293,1937,1,Home,24/08/2022,Hearth Harmony,0.151265,Medium
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
299995,565525,Men,25-34,Market Expansion,60 Days,Instagram,0.14,15000,4.950000,Los Angeles,English,39999,119998,7,Technology,17/10/2022,Code Crafters,0.333331,High
299996,539680,Women,25-34,Market Expansion,60 Days,Instagram,0.08,15000,3.410000,Austin,Spanish,39999,119998,8,Technology,25/02/2022,Innovate Infinity,0.333331,High
299997,140032,Women,35-44,Brand Awareness,60 Days,Pinterest,0.09,15000,0.904461,Miami,French,23492,77476,1,Food,02/10/2022,Gastronomy Guild,0.303216,Low
299998,161067,Women,18-24,Market Expansion,60 Days,Instagram,0.13,15000,7.430000,Las Vegas,Spanish,39999,119999,10,Food,24/01/2022,Savor Street,0.333328,High
299999,420183,Men,25-34,Brand Awareness,60 Days,Facebook,0.08,15000,1.900000,Miami,English,40000,120000,10,Technology,18/07/2022,Innovate Infinity,0.333333,Medium

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 300000 entries, 0 to 299999
Data columns (total 19 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   Campaign_ID       300000 non-null  int64
 1   Gender            300000 non-null  object
 2   Age Group         300000 non-null  object
 3   Campaign_Goal     300000 non-null  object
 4   Duration          300000 non-null  object
 5   Channel_Used      300000 non-null  object
 6   Conversion_Rate   300000 non-null  float64
 7   Acquisition_Cost  300000 non-null  int64
 8   ROI               300000 non-null  float64
 9   Location          300000 non-null  object
 10  Language          300000 non-null  object
 11  Clicks            300000 non-null  int64
 12  Impressions       300000 non-null  int64
 13  Engagement_Score  300000 non-null  int64
 14  Customer_Segment  300000 non-null  object
 15  Date              300000 non-null  object
 16  Company           300000 non-null  object
 17  CTR               300000 non-null  float64
 18  Performance Tier  300000 non-null  object
dtypes: float64(3), int64(5), object(11)
memory usage: 43.5+ MB

In [5]:
df.shape

(300000, 19)

In [7]:
df.describe()

,Campaign_ID,Conversion_Rate,Acquisition_Cost,ROI,Clicks,Impressions,Engagement_Score,CTR
count,300000.000000,300000.000000,300000.000000,300000.000000,300000.000000,300000.000000,300000.000000,300000.000000
mean,550444.804487,0.080009,7753.751003,3.177691,18153.670370,56034.236387,4.369217,0.314156
std,260252.586037,0.040563,4301.036208,2.461200,11027.023294,32583.136334,3.156492,0.024657
min,100001.000000,0.010000,500.000000,0.000000,293.000000,1937.000000,1.000000,0.151187
25%,325003.500000,0.050000,4122.000000,0.930000,8821.000000,28362.000000,1.000000,0.301698
50%,551164.500000,0.080000,7756.000000,2.670000,17230.000000,54098.000000,4.000000,0.325373
75%,776284.500000,0.110000,11385.000000,5.330000,26808.000000,80925.250000,7.000000,0.331266
max,999998.000000,0.150000,15000.000000,8.000000,40000.000000,120000.000000,10.000000,0.333333

In [8]:
df.isnull()

,Campaign_ID,Gender,Age Group,Campaign_Goal,Duration,Channel_Used,Conversion_Rate,Acquisition_Cost,ROI,Location,Language,Clicks,Impressions,Engagement_Score,Customer_Segment,Date,Company,CTR,Performance Tier
0,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
299995,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
299996,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
299997,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
299998,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
299999,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False

In [9]:
df.isnull().sum().sum()

np.int64(0)

In [10]:
df['Acquisition_Cost'].unique()[:10]

array([500, 501, 502, 503, 504, 505, 506, 507, 508, 509])

In [18]:
df['Acquisition_Cost'] = (
    df['Acquisition_Cost']
    .astype(str)
    .str.replace('$', '', regex=False)
    .str.replace(',', '', regex=False)
)

df['Acquisition_Cost'] = pd.to_numeric(df['Acquisition_Cost'], errors='coerce')

In [20]:
df['Date'] = pd.to_datetime(df['Date'], format='%d/%m/%Y')

In [21]:
df['Year'] = df['Date'].dt.year
df['Month'] = df['Date'].dt.month
df['Day'] = df['Date'].dt.day

In [22]:
df.drop('Date', axis=1, inplace=True)

In [23]:
df.isnull().sum()

Campaign_ID         0
Gender              0
Age Group           0
Campaign_Goal       0
Duration            0
Channel_Used        0
Conversion_Rate     0
Acquisition_Cost    0
ROI                 0
Location            0
Language            0
Clicks              0
Impressions         0
Engagement_Score    0
Customer_Segment    0
Company             0
CTR                 0
Performance Tier    0
Year                0
Month               0
Day                 0
dtype: int64

In [24]:
df = df.dropna()

In [25]:
df.cov(numeric_only=True)

,Campaign_ID,Conversion_Rate,Acquisition_Cost,ROI,Clicks,Impressions,Engagement_Score,CTR,Year,Month,Day
Campaign_ID,6.773141e+10,-8.028774,3.752128e+06,310.476673,8.342850e+06,2.537627e+07,1546.821723,12.812843,0.0,-3702.457196,-2159.052210
Conversion_Rate,-8.028774e+00,0.001645,3.621964e-01,-0.000025,9.149637e-01,2.714239e+00,-0.000255,0.000003,0.0,-0.000002,-0.000286
Acquisition_Cost,3.752128e+06,0.362196,1.849891e+07,-17.559732,4.390927e+07,1.322012e+08,-37.095557,60.244912,0.0,-50.385548,105.548535
ROI,3.104767e+02,-0.000025,-1.755973e+01,6.057507,5.111572e+03,1.331288e+04,2.755712,0.017756,0.0,0.010203,-0.007885
Clicks,8.342850e+06,0.914964,4.390927e+07,5111.571665,1.215952e+08,3.588526e+08,6964.658477,189.033834,0.0,-75.365680,199.742542
Impressions,2.537627e+07,2.714239,1.322012e+08,13312.876124,3.588526e+08,1.061661e+09,18127.385540,550.179249,0.0,-244.268804,624.280609
Engagement_Score,1.546822e+03,-0.000255,-3.709556e+01,2.755712,6.964658e+03,1.812739e+04,9.963442,0.024332,0.0,0.011373,-0.060062
CTR,1.281284e+01,0.000003,6.024491e+01,0.017756,1.890338e+02,5.501792e+02,0.024332,0.000608,0.0,-0.000085,-0.000413
Year,0.000000e+00,0.000000,0.000000e+00,0.000000,0.000000e+00,0.000000e+00,0.000000,0.000000,0.0,0.000000,0.000000
Month,-3.702457e+03,-0.000002,-5.038555e+01,0.010203,-7.536568e+01,-2.442688e+02,0.011373,-0.000085,0.0,11.891709,0.213071
Day,-2.159052e+03,-0.000286,1.055485e+02,-0.007885,1.997425e+02,6.242806e+02,-0.060062,-0.000413,0.0,0.213071,77.425692

In [31]:
df['Success'] = np.where(df['ROI'] > 3, 1, 0)

In [32]:
from sklearn.model_selection import train_test_split

X = df.drop('Success', axis=1)
Y = df['Success']

xtrain, xtest, ytrain, ytest = train_test_split(
    X, Y, test_size=0.2, random_state=42
)

In [33]:
df.drop('Campaign_ID', axis=1, inplace=True)

In [34]:
df['Success'] = np.where(df['ROI'] > 3, 1, 0)

In [35]:
X = df.drop('Success', axis=1)
Y = df['Success']

In [36]:
X = pd.get_dummies(X, drop_first=True)

In [37]:
X.dtypes

Conversion_Rate            float64
Acquisition_Cost           float64
ROI                        float64
Clicks                       int64
Impressions                  int64
                            ...
Company_Vogue Visions         bool
Company_Well Wish             bool
Company_Wellness Waves        bool
Performance Tier_Low          bool
Performance Tier_Medium       bool
Length: 86, dtype: object

In [38]:
xtrain, xtest, ytrain, ytest = train_test_split(
    X, Y, test_size=0.2, random_state=42
)

In [39]:
scaler = StandardScaler()
xtrain = scaler.fit_transform(xtrain)
xtest = scaler.transform(xtest)

In [40]:
logreg = LogisticRegression()
logreg.fit(xtrain, ytrain)

LogisticRegression()

In [41]:
y_pred = logreg.predict(xtest)
y_train_pred = logreg.predict(xtrain)

In [42]:
cm = confusion_matrix(ytest, y_pred)
print(cm)

[[31788     0]
 [    0 28212]]

In [43]:
accuracy_score(ytest, y_pred)

1.0

In [44]:
precision_score(ytest, y_pred)

1.0

In [45]:
recall_score(ytest, y_pred)

1.0

In [46]:
print("Confusion Matrix:\n", confusion_matrix(ytest, y_pred))
print("Accuracy:", accuracy_score(ytest, y_pred))
print("Precision:", precision_score(ytest, y_pred))
print("Recall:", recall_score(ytest, y_pred))

Confusion Matrix:
 [[31788     0]
 [    0 28212]]
Accuracy: 1.0
Precision: 1.0
Recall: 1.0

In [47]:
error_rate = 1 - accuracy_score(ytest, y_pred)
print("Error Rate:", error_rate)

Error Rate: 0.0